sudo: false
language: node_js
node_js:
 - node
cache: npm
branches:
  only:
  - master
before_script:
  - npm install yaspeller -g
script:
  - git diff --name-only HEAD...$TRAVIS_BRANCH --oneline # | grep "^rustbook-ru" | grep "*.md$" --color=never #| xargs yaspeller -c common-configs/.yaspellerrc
