sudo: false
language: node_js
node_js:
 - node
cache: npm
branches:
  only:
  - master
before_script:
  - npm install yaspeller -g
script:
  - if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then git diff --name-only $TRAVIS_PULL_REQUEST_BRANCH...master --oneline; fi #| grep "^rustbook-ru" | grep "*.md$" --color=never #| xargs yaspeller -c common-configs/.yaspellerrc
