name: Spellchecking
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  spellchecking:
    name: Checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - run: npm install -f yaspeller
    - run: git show -m --name-only -1 --format="format:" | grep --color=never '*.md' | xargs yaspeller -c common-configs/.yaspellerrc
