name: Spellchecking
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  spellchecking:
    name: Checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: diff
      run: git show -m --name-only -1 --format="format:"
