name: Spellchecking
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  spellchecking:
    name: Checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: diff
      runs: git diff master..$GITHUB_SHA
